//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regulazy.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Regulazy.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon Capture {
            get {
                object obj = ResourceManager.GetObject("Capture", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Demo_Simple {
            get {
                object obj = ResourceManager.GetObject("Demo_Simple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon EmptyMatch {
            get {
                object obj = ResourceManager.GetObject("EmptyMatch", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon FullMatch {
            get {
                object obj = ResourceManager.GetObject("FullMatch", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Group {
            get {
                object obj = ResourceManager.GetObject("Group", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Huh_ExpressionPane {
            get {
                object obj = ResourceManager.GetObject("Huh_ExpressionPane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Huh_RegexOptionsPane {
            get {
                object obj = ResourceManager.GetObject("Huh_RegexOptionsPane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Regulator {
            get {
                object obj = ResourceManager.GetObject("Regulator", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.$		Anything		-100
        ///^.+?$		1 or more anything		-110
        ///^.*?$		0 or more anything		-110
        ///^\w+?$		1 or more letters\numbers
        ///^\w$		letter or number
        ///^\\$		BackSlash
        ///^\t$		Tab
        ///^\t+$		Tabs
        ///^\r$		Carriege-Return
        ///^\r+$		Carriege-Returns
        ///^\v$		Vertical-Tab
        ///^\f$		Form Feed
        ///^\n$		New Line
        ///^\n+$		New-Lines
        ///^\e$		Escape
        ///^\s$		Whitespace		100
        ///^\s+$		1 or more Whitespaces		99
        ///^\s*$		0 or more Whitespaces		99
        ///^\d$		Digit		100
        ///^\d+$		Digits		99
        ///^\w+?@\w+\.\w{3,5}$		Email(Simple)		100
        ///^\d{2}/\d{2}/\d{4}$		Sh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RulesFile {
            get {
                return ResourceManager.GetString("RulesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public void SampleRegexUsage()
        ///{
        ///	string regex=@&quot;$REGEX$&quot;;
        ///	RegexOptions options = $REGEXOPTIONS_CS$;
        ///	string input= @&quot;$INPUT$&quot;;
        ///	
        ///	MatchCollection matches = Regex.Matches(input,regex,options);
        ///    foreach (Match match in matches)
        ///	{
        ///		Console.WriteLine(match.Value);
        ///        $FOREACH-GROUP$
        ///        Console.WriteLine(&quot;$GROUPNAME$:&quot; + match.Groups[&quot;$GROUPNAME$&quot;].Value);
        ///		$END-FOREACH-GROUP$
        ///	}
        ///}
        ///
        ///
        ///.
        /// </summary>
        internal static string Template_CS {
            get {
                return ResourceManager.GetString("Template_CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public Sub SampleRegexUsage()
        ///	Dim regex As String=&quot;$REGEX$&quot;
        ///	Dim options as RegexOptions = $REGEXOPTIONS_VB$
        ///	Dim input As String= &quot;$INPUT$&quot;
        ///	
        ///	Dim  matches As MatchCollection= Regex.Matches(input,regex,options)
        ///    For Each found As Match in matches
        ///		Console.WriteLine(found.Value)
        ///        $FOREACH-GROUP$
        ///        Console.WriteLine(&quot;$GROUPNAME$:&quot; &amp; match.Groups(&quot;$GROUPNAME$&quot;).Value)
        ///		$END-FOREACH-GROUP$
        ///    End For
        ///End Sub
        ///
        ///.
        /// </summary>
        internal static string Template_VB {
            get {
                return ResourceManager.GetString("Template_VB", resourceCulture);
            }
        }
    }
}
